<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*.volt</string>
	</array>
	<key>name</key>
	<string>volt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>storage.type.volt</string>
			<key>match</key>
			<string>\b(bool|char|dchar|wchar|i8|i16|i32|i64|u8|u16|u32|u64|f32|f64|string|size_t|ptrdiff_t|void|auto)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.volt</string>
			<key>match</key>
			<string>\b(if|while|do|for|foreach|with|switch|return|throw|default|case|goto|break|continue|else|foreach_reverse)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.volt</string>
			<key>match</key>
			<string>\b(fn|dg|import|module|version|class|struct|interface|enum|this|super|public|private|protected|override|assert|new|cast|scope|ref|out|const|scope|alias|abstract|@property|in|body|global|local|extern)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single</string>
			<key>begin</key>
			<string>'</key>
			<key>end</key>
			<string>'</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>begin</key>
			<string>`</key>
			<key>end</key>
			<string>`</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>begin</key>
			<string>"</key>
			<key>end</key>
			<string>"</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>\b(\d|\.)(\d|\.|_)*</string> <!-- TODO: Doesn't match the start of '.4'. -->
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block</string>
			<key>begin</key>
			<string>/\*</key>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block</string>
			<key>begin</key>
			<string>/\+</key>
			<key>end</key>
			<string>\+/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.documentation</string>
			<key>begin</key>
			<string>/\*\*</key>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.documentation</string>
			<key>begin</key>
			<string>/\+\+</key>
			<key>end</key>
			<string>\+/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line</string>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.volt</string>
</dict>
</plist>